default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails-simple-airbnb_development

test:
  <<: *default
  database: rails-simple-airbnb_test
